# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imager_images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='photo',
            new_name='photos',
        ),
    ]
